### ISSUE TITLE
Imposible to install Termite with ghc 7.10.3

### ISSUE THREAD

**Issue by alarreine** [termite2/Termite#16]
Hi, 
I'm trying to install Termite with ghc 7.10.3 but it is really hard, I'm not an expert in Haskell.

I followed the instruction but every time that I fix a problem, it appear another.

- I have changed the version of dependence in /lib in every 
- I have changed the lines where a newtype derive Monad and I added  Functor, Applicative because the version 7.10 require this
- In lib/debug/Debug/SourceView.hs:866 I had a problem of "Match expected type DefaultGlibString couldn't match type ‘[Char]’" and I have "import qualified Data.Text  as DT" and use "pack" function.

And now I have this in line  929:14

Could not deduce (glib-0.13.4.1:System.Glib.UTFString.GlibString string0) arising from a use of ‘G.labelNew’ from the context (D.Rel c v a s) bound by the type signature for sourceWindowCreate :: D.Rel c v a s => RSourceView c a u -> IO G.Widget at Debug/SourceView.hs:913:23-73 instance glib-0.13.4.1:System.Glib.UTFString.GlibString [Char] -- Defined in ‘glib-0.13.4.1:System.Glib.UTFString’ In a stmt of a 'do' block: lprog <- G.labelNew Nothing In the expression: do { vbox <- G.vBoxNew False 0; G.widgetShow vbox; spec <- getIORef svInputSpec ref; code <- codeWinNew spec; .... } In an equation for ‘sourceWindowCreate’: sourceWindowCreate ref = do { vbox <- G.vBoxNew False 0; G.widgetShow vbox; spec <- getIORef svInputSpec ref; cabal: Error: some packages failed to install:

I have done a fork in https://github.com/apd2 of all the project 

I'm not a haskell developer so I'm not sure if all I have done it is correct.

Thanks for your help in advance

**Comment by alexlegg** [comment]
Hi Agustin,

Termite is not really maintained any more so there's a good chance that trying to get it to work in newer versions of ghc will be tricky. I'd suggest using [stack](haskellstack.org) to compile it with an older version of ghc. As a starting point for your stack.yaml file, try looking at [this one](https://github.com/alexlegg/TermiteSAT/blob/master/stack.yaml) from my fork. I think the fork contains all of the Termite code unmodified, so the same ghc version _should_ work...

Alex

**Comment by alarreine** [comment]
Thanks, I'm goint to try

**Comment by adamwalker** [comment]
You can also try putting an upper bound on gtk. Probably one version earlier than the latest one. The errors look like they're related to glib, which gtk uses.

**Comment by alarreine** [comment]
Hi Adam,
wich ghc version and cabal have you used to compile the last time?

**Comment by AntoineBL** [comment]
Hello, we have fixed the bugs. You can find the correction here [apd2](https://github.com/apd2)
Thank you
